### ISSUE TITLE
Integrate invenio-stats into invenio-app-rdm

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-stats#121]
- [ ] how to handle cleaning of indices (to avoid growing the cluster)
- [x] investigate: replace the signals: do we use the message bus? If yes, it is a pre-requisites. Or, where to hook in? part of uow? part of the resource/service?
- [x] Verify the latest version of OpenSearch if there is any change how aggregation works, comparing to ES7
- [ ]  can we exclude admins/curators/owners from the stats calculation? how do we pass the current identity to the service correctly?

Investigate:
- [ ] migration to Counter v5
- [ ] adding more aggregations (country of visit, others)
Nice to have:
statistics per community (can be done as a part of the MS5+)

**Comment by kpsherva** [comment]
frontend mockups:
https://github.com/inveniosoftware/invenio-stats/issues/120

**Comment by max-moser** [comment]
Regarding the event bus as replacement for signals: According to last Friday's discussion, the event bus isn't as high priority as the general integration of the `Invenio-Stats` package.
As such, we will for now emit the relevant events right after the UoW committed (or as a post-action service component).

This means we're essentially skipping one step of event handlers for now, and shouldn't be too hard to add later.

**Comment by max-moser** [comment]
# Stats events & event bus: discussion recap

A brief summary of our discussions in Discord (February 7th, 2023) regarding the potentially upcoming event bus and the stats events:

## Where should events be emitted?

While the units of work (`uow`) for service methods would be a somewhat natural candidate for emitting events (via a kind of `TaskOp`), it should be noted that not all service methods have `uow`s right now: Read operations don't.
Adding units of work to read operations just for the sake of having a nice spot to emit events seems bad practice.
We don't intend to go down that route until there's further reasons for a `uow` there.
Also, the question of who emitted the event is less important than the fact that it _is_ being emitted – where it's emitted depends on the event itself.

For the initial integration of statistics events, we simply go for direct event emission in the `resources` and `view functions`.


## Should we count events for all endpoints?

There's multiple endpoints that touch the "reading" of a record (similar for file downloads), including:
* UI landing page
* UI export of record in various metadata schemas
* API endpoint for record metadata
* etc.

Collecting "record view" events for the UI seems like a no-brainer, while it's questionable whether we'd wanna count API endpoint calls.
For file downloads however, both UI and API need to be counted.

We decided to limit the `record-view` event emission to the landing page UI (view function in `app-rdm`) and the "read record" API endpoint (resource in `records-resources`) for now.
Events from these sources can be distinguished by a boolean flag in the event, called `via_api`.
This way, we can track record views from both the UI and the API, and filter out unwanted reads when querying for the statistics.

Similar for file downloads: `resources` in `app-rdm` and view functions in `records-resources`, distinguished by `via_api`.


## Single-Page Applications: out of scope (for now)

If some third party writes an SPA as an alternative InvenioRDM frontend, we don't have control over how that SPA interacts with the Invenio's REST API (e.g. they might cache API results, and thus "falsify" statistics, etc.).
These considerations are out of scope for now.

**Comment by max-moser** [comment]
The [OpenSearch changelog](https://opensearch.org/docs/latest/version-history/) doesn't mention any changes regarding to aggregations, and I haven't noticed anything weird either.
