### ISSUE TITLE
`doc_type`s are still referenced in the tests

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/invenio-stats#124]
Recent versions of ES and OS have dropped support for `doc_type`s, and thus we've removed references to them in the code base.
However, `doc_types` are still referenced in tests/test_cli.py (e.g. [here](https://github.com/max-moser/invenio-stats/blob/mm/update/tests/test_cli.py#L139)).

This doesn't seem to affect the success of the tests, but I'm not familiar enough with the module's inner workings (yet) to tell if that's okay or not.
What would be the proper course of action here?

**Comment by psaiz** [comment]
Could it be that this has been fixed in the mean time?
```
psaiz@mac-psaiz invenio-stats % git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
psaiz@mac-psaiz invenio-stats % git log -1
commit 850ac443ea03bbb5ee838b15a67cd952ffdbfa7a (HEAD -> master, origin/master, origin/HEAD)
Author: Javier Romero Castro <jrcastro9515@gmail.com>
Date:   Wed May 3 13:56:18 2023 +0200

    aggreagations: fix bug on list bookmarks
psaiz@mac-psaiz invenio-stats % grep -ri doc_type .
psaiz@mac-psaiz invenio-stats % 
```

**Comment by max-moser** [comment]
Yeah, looks like this issue is a left-over :)
