### ISSUE TITLE
global: avoid using "doc_type" for aggregations/bookmarks

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-stats#52]
Since document types [are pending deprecation](https://www.elastic.co/guide/en/elasticsearch/reference/6.x/removal-of-types.html) in upcoming ElasticSearch versions, it would be better to move event aggregation/bookmark document types to their own indices.

**Comment by topless** [comment]
This one has been addressed on previous sprint by @ChiaraBi

**Comment by slint** [comment]
Addressed in https://github.com/inveniosoftware/invenio-stats/commit/0fe253265663e1461b724bafa0b2c36f56b9f932
