### ISSUE TITLE
ES 7 support

### ISSUE THREAD

**Issue by ChiaraBi** [inveniosoftware/invenio-stats#81]
- [x] add prefix support (https://github.com/inveniosoftware/invenio-stats/pull/79)
- [x] bucket size: get the buckets cardinality and use it as the bucket size (https://github.com/inveniosoftware/invenio-stats/pull/80)
- [x] bookmarks: DocType has been deprecated
- [x] travis: add tests for es5, es6, es7 and remove tests for es2
- [ ] ~~remove all of the custom configuration: keep the files in `contrib`, but don't register them in `setup.py` (https://github.com/inveniosoftware/invenio-stats/pull/83)~~ (moved in https://github.com/inveniosoftware/invenio-stats/issues/86)
- [ ] ~~review documentation~~ (moved to https://github.com/inveniosoftware/invenio-stats/issues/87)

**Comment by slint** [comment]
Closed via #85
