### ISSUE TITLE
aggregations: use bucket partitioning to handle large number of unique buckets

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-stats#93]
During the aggregation query execution, if the number of buckets is too big (e.g. too many unique files/records viewed in a single day), the ES cluster or running Python process might come across memory issues.

To avoid that [bucket partitioning](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_with_partitions) should be used with the methods described in the ES docs.

**Comment by slint** [comment]
This feature has been implemented in `v1.0.0a14.post1` and `v1.0.0a14.post2`. Commits from these releases have to be cherry-picked in the current master branch and tested.

**Comment by topless** [comment]
This is related to #106
